# Generated by Django 3.0.7 on 2025-03-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Staffs')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('family_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('academic_achievements', models.TextField()),
                ('extra_curricular_achievements', models.TextField(blank=True, null=True)),
                ('purpose_statement', models.TextField()),
                ('supporting_documents', models.FileField(upload_to='scholarship_docs/')),
                ('hod_feedback', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.ScholarshipType')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Students')),
            ],
            options={
                'unique_together': {('scholarship_type', 'student_id', 'application_date')},
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('application_message', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Club')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Students')),
            ],
            options={
                'unique_together': {('club_id', 'student_id')},
            },
        ),
    ]
