# Generated by Django 3.0.7 on 2025-03-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_auto_20250308_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='previous_school',
        ),
        migrations.AddField(
            model_name='students',
            name='second_language',
            field=models.CharField(blank=True, choices=[('HI', 'Hindi'), ('ML', 'Malayalam')], max_length=2, null=True, verbose_name='Second Language'),
        ),
    ]
