# Generated by Django 3.0.7 on 2025-03-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_auto_20250309_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='caste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
